import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import { NextAuthProvider } from "@/components/NextAuthProvider";

const inter = Inter(
  { subsets: ["greek"] }
);


export const metadata: Metadata = {
  title: "Empty Point",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
      </head>
      <body className={inter.className}>
        <NextAuthProvider>
          <main className="flex-auto">{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}