name: deploy empty-point
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout
      uses: actions/checkout@v4
      
    - name: install nodejs
      uses: actions/setup-node@v4
      with: 
        node-version: 18.x

    - name: build project
      run: |
        cd next-js-app
        echo "${{ secrets.EMPTY_POINT_ENV }}" > .env
        npm install
        npm run build

    - name: deploy project
      run: |
        (mkdir .ssh) && (echo "${{ secrets.EMPTY_POINT_REMOTE_KEY }}" > .ssh/id_rsa) && (chmod 600 .ssh/id_rsa)
        ssh deploy@${{ vars.EMPTY_POINT_REMOTE_HOST }} 'rm -rf empty-point'
        scp empty-point deploy@${{ vars.EMPTY_POINT_REMOTE_HOST }}:empty-point
        
