name: deploy empty-point
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout
      uses: actions/checkout@v4
      
    - name: install nodejs
      uses: actions/setup-node@v4
      with: 
        node-version: 18.x

    - name: build project
      run: |
        cd next-js-app
        echo "${{ secrets.EMPTY_POINT_ENV }}" > .env
        npm install
        npm run build

    - name: deploy project
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: 'deploy'
        server: '${{ vars.EMPTY_POINT_REMOTE_HOST }}'
        ssh_private_key:  ${{ secrets.EMPTY_POINT_REMOTE_KEY }}
        local_path: './*'
        remote_path: '/home/deploy/empty-point'
        sftpArgs: ''
