name: deploy empty-point
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout
      uses: actions/checkout@v4
      
    - name: install nodejs
      uses: actions/setup-node@v4
      with: 
        node-version: 18.x

    - name: build project
      run: |
        cd next-js-app
        echo "${{ secrets.EMPTY_POINT_ENV }}" > .env
        npm install
        npm run build
        rm -rf node_modules

    - name: deploy project
      uses: appleboy/scp-action@master
      with:
        username: 'deploy'
        host: '${{ vars.EMPTY_POINT_REMOTE_HOST }}'
        key: ${{ secrets.EMPTY_POINT_REMOTE_KEY }}
        source: './*'
        target: '/home/deploy/empty-point'
        
