name: deploy empty-point
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps: 
    #- name: checkout
    #  uses: actions/checkout@v4
      
    #- name: install nodejs
    #  uses: actions/setup-node@v4
    #  with: 
    #    node-version: 18.x
    
    #- run: |
    #    cd next-js-app
    #    echo "${{ secrets.EMPTY_POINT_ENV }}" > .env
    #    npm install
    #    npm run build

    - run: |
        echo "${{ vars.EMPTY_POINT_REMOTE_HOST }}"
