name: deploy empty-point
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout
      uses: actions/checkout@v4
      
    - name: install nodejs
      uses: actions/setup-node@v4
      with: 
        node-version: 18.x
    
    - run: |
        cd next-js-app
        echo "${{ secrets.EMPTY_POINT_ENV }}" > .env
        npm install
        npm run build

    - name: scp project
      uses: appleboy/scp-action@v0.0.1
      with:
        host: ${{ secrets.EMPTY_POINT_REMOTE_HOST }}
        key: ${{ secrets.EMPTY_POINT_REMOTE_KEY }}
        username: deploy
        source: '.'
        target: '/home/deploy/empty-point/'
        args: '-r'
