name: deploy empty-point
on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps: 
    - name: checkout
      uses: actions/checkout@v4
      
    - name: install nodejs
      uses: actions/setup-node@v4
      with: 
        node-version: 18.x
    
    - run: |
        cd next-js-app
        echo "${{ secrets.EMPTY_POINT_ENV }}" > .env
        npm install
        npm run build

    - run: |
        mkdir .ssh
        ehco "${{ secrets.EMPTY_POINT_REMOTE_KEY }}" > .ssh/id_rsa

    - name: ssh deploy
    - uses: easingthemes/ssh-deploy@main
      with:
        REMOTE_HOST: ${{ vars.EMPTY_POINT_REMOTE_HOST }}
        REMOTE_USER: deploy
        SCRIPT_BEFORE: |
          rm -rf empty-point
        SOURCE: 'empty-point'
        TARGET: 'empty-point'
        
